package com.loiane.contract;

import static org.mockito.Mockito.when;

import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.bean.override.mockito.MockitoBean;

import com.loiane.course.CourseService;
import com.loiane.course.dto.CourseDTO;
import com.loiane.course.dto.CoursePageDTO;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;

/**
 * Replays the pact generated by the Angular consumer (crud-angular) against the
 * real {@link CourseService} boundary. The application is booted on a random
 * port and Pact issues real HTTP requests, so the actual controller and Jackson
 * serialization path are exercised. If the JSON the backend produces ever stops
 * matching what the Angular app depends on, this test fails on the producer's
 * own build.
 *
 * <p>Note: Pact JVM's {@code MockMvcTestTarget} (as shown in the blog post) is
 * compiled against Spring 6 and is binary-incompatible with the Spring Framework
 * 7 that ships in Spring Boot 4.x. Using {@link HttpTestTarget} against a real
 * server sidesteps that and verifies the true HTTP response.
 */
@Provider("crud-spring")
@PactFolder("../crud-angular/pacts")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class CourseContractVerificationTest {

    @LocalServerPort
    private int port;

    @MockitoBean
    private CourseService courseService;

    @BeforeEach
    void setTarget(PactVerificationContext context) {
        context.setTarget(new HttpTestTarget("localhost", port));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void verifyPact(PactVerificationContext context) {
        context.verifyInteraction();
    }

    @State("three courses exist")
    void threeCoursesExist() {
        when(courseService.findAll(0, 10)).thenReturn(
                new CoursePageDTO(List.of(
                        new CourseDTO(1L, "Angular", "Front-end", List.of()),
                        new CourseDTO(2L, "Spring Boot", "Back-end", List.of()),
                        new CourseDTO(3L, "Java", "Back-end", List.of())), 3, 1));
    }
}
